/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// @ts-ignore
import XLSX from 'xlsx-js-style';

// Format report date-time string consistently
export function formatReportDate(dateVal: any): string {
  if (!dateVal || dateVal === 'N/A' || dateVal === 'Not Available') return 'Not Available';
  try {
    const d = new Date(dateVal);
    if (isNaN(d.getTime())) return String(dateVal);
    const day = String(d.getDate()).padStart(2, '0');
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    const month = months[d.getMonth()];
    const year = d.getFullYear();
    return `${day} ${month} ${year}`;
  } catch (e) {
    return String(dateVal);
  }
}

export function formatReportTime(dateVal: any): string {
  if (!dateVal || dateVal === 'N/A' || dateVal === 'Not Available') return 'Not Available';
  try {
    const d = new Date(dateVal);
    if (isNaN(d.getTime())) return String(dateVal);
    let hours = d.getHours();
    const minutes = String(d.getMinutes()).padStart(2, '0');
    const ampm = hours >= 12 ? 'PM' : 'AM';
    hours = hours % 12;
    hours = hours ? hours : 12;
    return `${String(hours).padStart(2, '0')}:${minutes} ${ampm}`;
  } catch (e) {
    return String(dateVal);
  }
}

export function formatReportDateTime(dateVal: any): string {
  if (!dateVal || dateVal === 'N/A' || dateVal === 'Not Available') return 'Not Available';
  try {
    const d = new Date(dateVal);
    if (isNaN(d.getTime())) return String(dateVal);
    return `${formatReportDate(dateVal)} ${formatReportTime(dateVal)}`;
  } catch (e) {
    return String(dateVal);
  }
}

// Escape XML Special Characters
export function escapeXML(val: any): string {
  if (val === null || val === undefined) return '';
  return String(val)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// Map column header to its optimal Excel column width (points)
export function getColumnWidth(header: string): number {
  const h = header.toLowerCase().trim();
  if (h.includes('student name') || h.includes('full name') || h.includes('name')) return 220;
  if (h.includes('usn')) return 120;
  if (h.includes('department') || h.includes('branch')) return 200;
  if (h.includes('email')) return 220;
  if (h.includes('semester')) return 90;
  if (h.includes('section')) return 90;
  if (h.includes('role')) return 100;
  if (h.includes('session name') || h.includes('session title') || h.includes('session')) return 200;
  if (h.includes('session date') || h.includes('date')) return 130;
  if (h.includes('venue')) return 90;
  if (h.includes('status')) return 110;
  if (h.includes('check-in') || h.includes('time')) return 140;
  if (h.includes('method') || h.includes('verification')) return 160;
  if (h.includes('assignment')) return 200;
  if (h.includes('due date') || h.includes('deadline')) return 135;
  if (h.includes('submitted')) return 155;
  if (h.includes('completion')) return 155;
  if (h.includes('marked by')) return 165;
  if (h.includes('marked at')) return 165;
  if (h.includes('feedback')) return 240;
  return 100; // Default fallback width
}

// Format data and trigger browser download of high-compatibility CSV string
export function exportToCSV(
  filename: string,
  headers: string[],
  rows: string[][],
  reportName?: string,
  userName?: string
) {
  if (typeof window !== 'undefined') (window as any).inactivityTimeoutPaused = true;
  try {
    const actualReportName = reportName || filename.replace(/_/g, ' ').replace(/Report/gi, '').trim() + ' Report';
    const dateStr = formatReportDateTime(new Date());

    const contentRows: string[][] = [
      ['SMART ATTENDANCE HUB'],
      [actualReportName],
      [`Generated On: ${dateStr}`],
      [`Generated By: ${userName || 'Administrator'}`],
      [],
      headers,
      ...rows,
      [],
      ['Generated by Smart Attendance Hub']
    ];

    const csvContent = contentRows.map(row => 
      row.map(val => {
        if (val === null || val === undefined) return '';
        // Escape inner quotes
        const clean = String(val).replace(/"/g, '""');
        // Quote value if it contains special CSV characters
        return clean.includes(',') || clean.includes('\n') || clean.includes('"') ? `"${clean}"` : clean;
      }).join(',')
    ).join('\r\n');

    // Prepend UTF-8 BOM (\uFEFF) for Microsoft Excel compatibility
    const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `${filename}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } finally {
    if (typeof window !== 'undefined') (window as any).inactivityTimeoutPaused = false;
  }
}

// Generate a true Excel (.xlsx) workbook with SheetJS (xlsx-js-style) containing worksheets, styling, and freeze pane configuration
export function exportToExcel(
  filename: string,
  reportName: string,
  userName: string,
  sheets: {
    name: string;
    sections: {
      title?: string;
      headers?: string[];
      rows: string[][];
      isKeyValue?: boolean;
    }[];
  }[]
) {
  if (typeof window !== 'undefined') (window as any).inactivityTimeoutPaused = true;
  try {
    const dateStr = formatReportDateTime(new Date());
  const wb = XLSX.utils.book_new();

  // Helper to safely write cell data
  function addCell(ws: any, r: number, c: number, val: any, style: any, type: string = 's') {
    const cellRef = XLSX.utils.encode_cell({ r, c });
    ws[cellRef] = {
      v: val,
      t: type,
      s: style
    };
  }

  // Helper to write merged cells with consistent styling across all merged coordinates
  function addMergedRange(ws: any, startR: number, startC: number, endR: number, endC: number, val: any, style: any) {
    if (!ws['!merges']) ws['!merges'] = [];
    ws['!merges'].push({ s: { r: startR, c: startC }, e: { r: endR, c: endC } });

    for (let r = startR; r <= endR; r++) {
      for (let c = startC; c <= endC; c++) {
        const cellRef = XLSX.utils.encode_cell({ r, c });
        ws[cellRef] = {
          v: (r === startR && c === startC) ? val : '',
          t: 's',
          s: style
        };
      }
    }
  }

  sheets.forEach(sheet => {
    const ws: any = {
      '!merges': [],
      '!cols': [],
      '!rows': [],
      '!views': [{ state: 'frozen', ySplit: 5 }],
      '!pageSetup': {
        orientation: 'landscape',
        paperSize: 9 // A4 Landscape
      },
      '!margins': { left: 0.5, right: 0.5, top: 0.5, bottom: 0.5, header: 0.3, footer: 0.3 }
    };

    // Calculate maximum columns in the sheet (minimum 5 columns so Title and Metadata center beautifully)
    let maxCols = 5;
    sheet.sections.forEach(sec => {
      if (sec.headers && sec.headers.length > maxCols) {
        maxCols = sec.headers.length;
      }
      if (sec.rows && sec.rows.length > 0) {
        sec.rows.forEach(row => {
          if (row.length > maxCols) {
            maxCols = row.length;
          }
        });
      }
    });

    const colWidths = Array(maxCols).fill(110); // base default pixel width (110px)
    const rowHeights: number[] = [];

    // Title Row (Row 0) - Centered & Bold
    const titleStyle = {
      font: { name: 'Segoe UI', sz: 16, bold: true, color: { rgb: '1E3A8A' } },
      alignment: { horizontal: 'center', vertical: 'center' },
      fill: { fgColor: { rgb: 'F1F5F9' } },
      border: {
        top: { style: 'thin', color: { rgb: 'CBD5E1' } },
        bottom: { style: 'thin', color: { rgb: 'CBD5E1' } },
        left: { style: 'thin', color: { rgb: 'CBD5E1' } },
        right: { style: 'thin', color: { rgb: 'CBD5E1' } }
      }
    };
    addMergedRange(ws, 0, 0, 0, maxCols - 1, 'SMART ATTENDANCE HUB', titleStyle);
    rowHeights[0] = 38;

    // Report Name (Row 1) - Centered & Bold
    const subtitleStyle = {
      font: { name: 'Segoe UI', sz: 12, bold: true, color: { rgb: '0F172A' } },
      alignment: { horizontal: 'center', vertical: 'center' },
      fill: { fgColor: { rgb: 'F1F5F9' } },
      border: {
        left: { style: 'thin', color: { rgb: 'CBD5E1' } },
        right: { style: 'thin', color: { rgb: 'CBD5E1' } }
      }
    };
    addMergedRange(ws, 1, 0, 1, maxCols - 1, reportName, subtitleStyle);
    rowHeights[1] = 26;

    // Generated On (Row 2) - Metadata section below title
    const metaStyle1 = {
      font: { name: 'Segoe UI', sz: 9.5, italic: true, color: { rgb: '475569' } },
      alignment: { horizontal: 'center', vertical: 'center' },
      fill: { fgColor: { rgb: 'F1F5F9' } },
      border: {
        left: { style: 'thin', color: { rgb: 'CBD5E1' } },
        right: { style: 'thin', color: { rgb: 'CBD5E1' } }
      }
    };
    addMergedRange(ws, 2, 0, 2, maxCols - 1, `Generated On: ${dateStr}`, metaStyle1);
    rowHeights[2] = 20;

    // Generated By (Row 3) - Metadata section below title
    const metaStyle2 = {
      font: { name: 'Segoe UI', sz: 9.5, italic: true, color: { rgb: '475569' } },
      alignment: { horizontal: 'center', vertical: 'center' },
      fill: { fgColor: { rgb: 'F1F5F9' } },
      border: {
        left: { style: 'thin', color: { rgb: 'CBD5E1' } },
        right: { style: 'thin', color: { rgb: 'CBD5E1' } },
        bottom: { style: 'thin', color: { rgb: 'CBD5E1' } }
      }
    };
    addMergedRange(ws, 3, 0, 3, maxCols - 1, `Generated By: ${userName}`, metaStyle2);
    rowHeights[3] = 20;

    // Spacer Row (Row 4)
    rowHeights[4] = 15;

    let currRow = 5;

    sheet.sections.forEach(sec => {
      // Section Header with Dark Blue Background & White Bold text with good contrast
      if (sec.title) {
        const sectionHeadingStyle = {
          font: { name: 'Segoe UI', sz: 11, bold: true, color: { rgb: 'FFFFFF' } },
          alignment: { horizontal: 'left', vertical: 'center', indent: 1 },
          fill: { fgColor: { rgb: '1E3A8A' } }, // Professional Dark Navy Blue background
          border: {
            top: { style: 'thin', color: { rgb: '1E3A8A' } },
            bottom: { style: 'medium', color: { rgb: '0F172A' } },
            left: { style: 'thin', color: { rgb: '1E3A8A' } },
            right: { style: 'thin', color: { rgb: '1E3A8A' } }
          }
        };
        addMergedRange(ws, currRow, 0, currRow, maxCols - 1, sec.title, sectionHeadingStyle);
        rowHeights[currRow] = 28;
        currRow++;
      }

      // If key-value info layout (e.g. Student Information, Performance Summary)
      if (sec.isKeyValue) {
        // Enforce strong minimum width for key and value columns so Student Name, Department, Email don't split/wrap
        colWidths[0] = Math.max(colWidths[0], 180); // Keys column
        colWidths[1] = Math.max(colWidths[1], 320); // Values column (Student Name, Department, Email, etc.)

        sec.rows.forEach(row => {
          const kvKeyStyle = {
            font: { name: 'Segoe UI', sz: 10, bold: true, color: { rgb: '475569' } },
            fill: { fgColor: { rgb: 'F8FAFC' } },
            alignment: { horizontal: 'left', vertical: 'center', indent: 1 },
            border: {
              top: { style: 'thin', color: { rgb: 'CBD5E1' } },
              bottom: { style: 'thin', color: { rgb: 'CBD5E1' } },
              left: { style: 'thin', color: { rgb: 'CBD5E1' } },
              right: { style: 'thin', color: { rgb: 'CBD5E1' } }
            }
          };

          const kvValStyle = {
            font: { name: 'Segoe UI', sz: 10, color: { rgb: '0F172A' } },
            fill: { fgColor: { rgb: 'FFFFFF' } },
            alignment: { horizontal: 'left', vertical: 'center' },
            border: {
              top: { style: 'thin', color: { rgb: 'CBD5E1' } },
              bottom: { style: 'thin', color: { rgb: 'CBD5E1' } },
              left: { style: 'thin', color: { rgb: 'CBD5E1' } },
              right: { style: 'thin', color: { rgb: 'CBD5E1' } }
            }
          };

          const keyLen = String(row[0] || '').length;
          colWidths[0] = Math.max(colWidths[0], Math.min(220, keyLen * 8.5 + 35));

          const valStr = String(row[1] || '');
          const valLen = valStr.length;
          const contentWidth = valLen * 8 + 35;
          colWidths[1] = Math.max(colWidths[1], Math.min(380, contentWidth));

          addCell(ws, currRow, 0, row[0], kvKeyStyle);
          addMergedRange(ws, currRow, 1, currRow, maxCols - 1, row[1], kvValStyle);
          rowHeights[currRow] = 22;
          currRow++;
        });

        // Small spacer after KV group
        rowHeights[currRow] = 12;
        currRow++;
      } else {
        // Table headers (if present)
        let headerRowIdx = -1;
        if (sec.headers) {
          headerRowIdx = currRow;
          sec.headers.forEach((h, idx) => {
            const headerStyle = {
              font: { name: 'Segoe UI', sz: 10.5, bold: true, color: { rgb: 'FFFFFF' } },
              fill: { fgColor: { rgb: '1E40AF' } }, // Slate/Royal Blue Header
              alignment: { horizontal: 'center', vertical: 'center', wrapText: false },
              border: {
                top: { style: 'thin', color: { rgb: '3B82F6' } },
                bottom: { style: 'medium', color: { rgb: '1E3A8A' } },
                left: { style: 'thin', color: { rgb: '3B82F6' } },
                right: { style: 'thin', color: { rgb: '3B82F6' } }
              }
            };
            addCell(ws, currRow, idx, h, headerStyle);

            const defaultWidth = getColumnWidth(h);
            colWidths[idx] = Math.max(colWidths[idx], defaultWidth + 25);
          });
          rowHeights[currRow] = 26;
          currRow++;
        }

        // Table Data rows
        if (sec.rows.length === 0) {
          const emptyStyle = {
            font: { name: 'Segoe UI', sz: 10, italic: true, color: { rgb: '94A3B8' } },
            alignment: { horizontal: 'center', vertical: 'center' },
            fill: { fgColor: { rgb: 'FFFFFF' } },
            border: {
              top: { style: 'thin', color: { rgb: 'CBD5E1' } },
              bottom: { style: 'thin', color: { rgb: 'CBD5E1' } },
              left: { style: 'thin', color: { rgb: 'CBD5E1' } },
              right: { style: 'thin', color: { rgb: 'CBD5E1' } }
            }
          };
          addMergedRange(ws, currRow, 0, currRow, maxCols - 1, 'No Records Available', emptyStyle);
          rowHeights[currRow] = 24;
          currRow++;
        } else {
          sec.rows.forEach((row, rowIdx) => {
            row.forEach((cell, cellIdx) => {
              let isNumeric = false;
              let numericVal = 0;
              const strVal = cell === null || cell === undefined ? '' : String(cell);

              if (strVal.trim() !== '' && !isNaN(Number(strVal)) && !strVal.includes('-') && !strVal.includes('/') && !strVal.includes(':') && strVal.length < 10) {
                isNumeric = true;
                numericVal = Number(strVal);
              }

              // Determine visual alignment
              const hText = (sec.headers && sec.headers[cellIdx] || '').toLowerCase();
              const isCenterAligned = cellIdx === 0 || 
                                     isNumeric || 
                                     strVal.length <= 10 || 
                                     hText.includes('sl no') || 
                                     hText.includes('status') || 
                                     hText.includes('method') || 
                                     hText.includes('date') ||
                                     hText.includes('time');

              // Enable text wrapping only when text is exceptionally long (> 40 chars)
              const needsWrap = strVal.length > 40 || hText.includes('description') || hText.includes('details');

              const cellStyle = {
                font: { name: 'Segoe UI', sz: 10, color: { rgb: '111827' } },
                fill: { fgColor: { rgb: rowIdx % 2 === 1 ? 'F8FAFC' : 'FFFFFF' } },
                alignment: {
                  horizontal: isCenterAligned ? 'center' : 'left',
                  vertical: 'center',
                  wrapText: needsWrap
                },
                border: {
                  top: { style: 'thin', color: { rgb: 'CBD5E1' } },
                  bottom: { style: 'thin', color: { rgb: 'CBD5E1' } },
                  left: { style: 'thin', color: { rgb: 'CBD5E1' } },
                  right: { style: 'thin', color: { rgb: 'CBD5E1' } }
                }
              };

              addCell(ws, currRow, cellIdx, isNumeric ? numericVal : strVal, cellStyle, isNumeric ? 'n' : 's');

              // Advanced AutoFit column width calculations with strict minimums
              const charLength = strVal.length;
              let contentWidth = charLength * 7.5 + 30;

              if (hText.includes('name') || hText.includes('title')) {
                contentWidth = Math.max(contentWidth, 190);
              } else if (hText.includes('email')) {
                contentWidth = Math.max(contentWidth, 230);
              } else if (hText.includes('date') || hText.includes('time')) {
                contentWidth = Math.max(contentWidth, 140);
              }

              colWidths[cellIdx] = Math.max(colWidths[cellIdx], Math.min(360, contentWidth));
            });

            rowHeights[currRow] = 22;
            currRow++;
          });

          // Enable autofilter across the table range if applicable
          if (headerRowIdx !== -1 && sec.headers) {
            const startCell = XLSX.utils.encode_cell({ r: headerRowIdx, c: 0 });
            const endCell = XLSX.utils.encode_cell({ r: currRow - 1, c: sec.headers.length - 1 });
            ws['!autofilter'] = { ref: `${startCell}:${endCell}` };
          }
        }

        // Spacer row after section
        rowHeights[currRow] = 15;
        currRow++;
      }
    });

    // Sheet footer
    const footerStyle = {
      font: { name: 'Segoe UI', sz: 9, italic: true, color: { rgb: '94A3B8' } },
      alignment: { horizontal: 'center', vertical: 'center' }
    };
    addMergedRange(ws, currRow, 0, currRow, maxCols - 1, 'Generated by Smart Attendance Hub', footerStyle);
    rowHeights[currRow] = 22;
    currRow++;

    // Save final worksheet configurations
    ws['!ref'] = XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: currRow - 1, c: maxCols - 1 } });
    ws['!cols'] = colWidths.map(w => ({ wpx: w }));
    ws['!rows'] = rowHeights.map(h => ({ hpt: h || 22 }));

    XLSX.utils.book_append_sheet(wb, ws, sheet.name);
  });

    XLSX.writeFile(wb, `${filename}.xlsx`);
  } finally {
    if (typeof window !== 'undefined') (window as any).inactivityTimeoutPaused = false;
  }
}

// Generate a simple single-table Excel sheet
export function exportSingleTableToExcel(
  filename: string,
  reportName: string,
  userName: string,
  sheetName: string,
  headers: string[],
  rows: string[][]
) {
  exportToExcel(filename, reportName, userName, [
    {
      name: sheetName,
      sections: [
        {
          headers,
          rows,
          isKeyValue: false
        }
      ]
    }
  ]);
}

// Print formatted HTML/PDF reports
export function printFormattedReport(
  title: string,
  subtitle: string,
  headers: string[],
  rows: string[][],
  summaryStats?: Record<string, string | number>
) {
  if (typeof window !== 'undefined') (window as any).inactivityTimeoutPaused = true;
  try {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

  const statsHtml = summaryStats 
    ? `<div class="stats-grid">
         ${Object.entries(summaryStats).map(([key, val]) => `
           <div class="stat-card">
             <div class="stat-label">${key}</div>
             <div class="stat-value">${val}</div>
           </div>
         `).join('')}
       </div>`
    : '';

  printWindow.document.write(`
    <html>
      <head>
        <title>${title}</title>
        <style>
          body {
            font-family: "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, sans-serif;
            color: #111827;
            padding: 40px;
            background: #ffffff;
          }
          .header {
            margin-bottom: 30px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 20px;
          }
          h1 {
            margin: 0 0 5px 0;
            font-size: 24px;
            color: #1e3a8a;
          }
          p {
            margin: 0;
            color: #4b5563;
            font-size: 14px;
          }
          .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
            gap: 15px;
            margin-bottom: 30px;
          }
          .stat-card {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 15px;
            border-radius: 8px;
          }
          .stat-label {
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: #4b5563;
            margin-bottom: 5px;
          }
          .stat-value {
            font-size: 18px;
            font-weight: 600;
            color: #111827;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
          }
          th {
            background: #1e3a8a;
            text-align: left;
            padding: 12px;
            font-size: 12px;
            text-transform: uppercase;
            color: #ffffff;
            border-bottom: 2px solid #cbd5e1;
          }
          td {
            padding: 12px;
            font-size: 13px;
            border-bottom: 1px solid #e2e8f0;
            color: #111827;
          }
          tr:nth-child(even) {
            background: #f8fafc;
          }
          .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 20px;
          }
          @media print {
            body { padding: 20px; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${title}</h1>
          <p>${subtitle} &bull; Generated on ${formatReportDateTime(new Date())}</p>
        </div>
        
        ${statsHtml}

        <table>
          <thead>
            <tr>
              ${headers.map(h => `<th>${h}</th>`).join('')}
            </tr>
          </thead>
          <tbody>
            ${rows.length === 0 ? `
              <tr>
                <td colspan="${headers.length}" style="text-align: center; color: #6b7280;">No Records Available</td>
              </tr>
            ` : rows.map(row => `
              <tr>
                ${row.map(cell => `<td>${cell || '-'}</td>`).join('')}
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="footer">
          Generated by Smart Attendance Hub &copy; ${new Date().getFullYear()} &bull; Professional Educational Tracking Systems
        </div>

        <script>
          window.onload = function() {
            window.print();
          };
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
  } finally {
    if (typeof window !== 'undefined') (window as any).inactivityTimeoutPaused = false;
  }
}
